@REM Array language tests.
@REM
@REM These exercise the array RTL actions end-to-end through the executor.
@REM Tests pass pre-parsed postfix to `:_run` / `:_runErr` so they run fast;
@REM the BASIC source equivalent is in a comment above each test for
@REM readability. Postfix was generated by running the source through
@REM `lexer ParseTxt` + `parse parse` and captured.
@REM
@REM Conventions:
@REM   :_run    "postfix"  "expected stdout (single line)"
@REM   :_runErr "postfix"   expected_errorlevel
@REM
@REM Each test starts with a fresh _vars and _arrays state.


@REM ============================================================
@REM  1-D arrays: assign and read
@REM ============================================================

call %test% "arr.1d.assign.read"
  @REM DIM A(3) : A(1) = 100 : PRINT A(1)
  call :_run "VAR_UNK_A ARR_START NUM_i0003 DIM VAR_UNK_A ARR_START NUM_i0001 NUM_i0064 ASSIGN_ARR VAR_UNK_A ARR_START NUM_i0001 AIDX PEND" " 100"

call %test% "arr.1d.zero.index.is.valid"
  @REM DIM A(3) : A(0) = 42 : PRINT A(0)
  @REM Default OPTION BASE 0 — element 0 is a valid index.
  call :_run "VAR_UNK_A ARR_START NUM_i0003 DIM VAR_UNK_A ARR_START NUM_i0000 NUM_i002A ASSIGN_ARR VAR_UNK_A ARR_START NUM_i0000 AIDX PEND" " 42"

call %test% "arr.1d.default.zero"
  @REM DIM A(3) : PRINT A(0)
  @REM Unassigned element reads as 0.
  call :_run "VAR_UNK_A ARR_START NUM_i0003 DIM VAR_UNK_A ARR_START NUM_i0000 AIDX PEND" " 0"

call %test% "arr.1d.upper.bound.inclusive"
  @REM DIM A(3) : A(3) = 11 : PRINT A(3)
  @REM DIM A(3) gives valid indices 0,1,2,3 (total 4 elements).
  call :_run "VAR_UNK_A ARR_START NUM_i0003 DIM VAR_UNK_A ARR_START NUM_i0003 NUM_i000B ASSIGN_ARR VAR_UNK_A ARR_START NUM_i0003 AIDX PEND" " 11"

call %test% "arr.1d.smallest.array"
  @REM DIM A(0) : A(0) = 5 : PRINT A(0)
  @REM DIM A(0) creates a 1-element array, index 0 only.
  call :_run "VAR_UNK_A ARR_START NUM_i0000 DIM VAR_UNK_A ARR_START NUM_i0000 NUM_i0005 ASSIGN_ARR VAR_UNK_A ARR_START NUM_i0000 AIDX PEND" " 5"


@REM ============================================================
@REM  Bounds errors (1-D)
@REM ============================================================

call %test% "arr.bounds.read.over.upper"
  @REM DIM A(3) : PRINT A(4)
  @REM Subscript out of range = err 9.
  call :_runErr "VAR_UNK_A ARR_START NUM_i0003 DIM VAR_UNK_A ARR_START NUM_i0004 AIDX PEND" 9

call %test% "arr.bounds.read.far.over"
  @REM DIM A(3) : PRINT A(100)
  call :_runErr "VAR_UNK_A ARR_START NUM_i0003 DIM VAR_UNK_A ARR_START NUM_i0064 AIDX PEND" 9

call %test% "arr.bounds.read.negative"
  @REM DIM A(3) : PRINT A(-1)
  @REM Negative subscript = err 5 (Illegal function call).
  call :_runErr "VAR_UNK_A ARR_START NUM_i0003 DIM VAR_UNK_A ARR_START NUM_i0001 NEG AIDX PEND" 5

call %test% "arr.bounds.write.over.upper"
  @REM DIM A(3) : A(100) = 99
  call :_runErr "VAR_UNK_A ARR_START NUM_i0003 DIM VAR_UNK_A ARR_START NUM_i0064 NUM_i0063 ASSIGN_ARR" 9

call %test% "arr.bounds.write.negative"
  @REM DIM A(3) : A(-1) = 99
  call :_runErr "VAR_UNK_A ARR_START NUM_i0003 DIM VAR_UNK_A ARR_START NUM_i0001 NEG NUM_i0063 ASSIGN_ARR" 5


@REM ============================================================
@REM  Multi-dim
@REM ============================================================

call %test% "arr.2d.assign.read"
  @REM DIM B(2,3) : B(1,2) = 55 : PRINT B(1,2)
  call :_run "VAR_UNK_B ARR_START NUM_i0002 NUM_i0003 DIM VAR_UNK_B ARR_START NUM_i0001 NUM_i0002 NUM_i0037 ASSIGN_ARR VAR_UNK_B ARR_START NUM_i0001 NUM_i0002 AIDX PEND" " 55"

call %test% "arr.2d.zero.zero"
  @REM DIM B(2,3) : PRINT B(0,0)
  call :_run "VAR_UNK_B ARR_START NUM_i0002 NUM_i0003 DIM VAR_UNK_B ARR_START NUM_i0000 NUM_i0000 AIDX PEND" " 0"

call %test% "arr.2d.both.corners"
  @REM DIM B(2,3) : B(2,3) = 99 : PRINT B(2,3)
  @REM Both bounds inclusive.
  call :_run "VAR_UNK_B ARR_START NUM_i0002 NUM_i0003 DIM VAR_UNK_B ARR_START NUM_i0002 NUM_i0003 NUM_i0063 ASSIGN_ARR VAR_UNK_B ARR_START NUM_i0002 NUM_i0003 AIDX PEND" " 99"

call %test% "arr.2d.bounds.first.dim"
  @REM DIM B(2,3) : PRINT B(3,0)
  call :_runErr "VAR_UNK_B ARR_START NUM_i0002 NUM_i0003 DIM VAR_UNK_B ARR_START NUM_i0003 NUM_i0000 AIDX PEND" 9

call %test% "arr.2d.bounds.second.dim"
  @REM DIM B(2,3) : PRINT B(0,4)
  call :_runErr "VAR_UNK_B ARR_START NUM_i0002 NUM_i0003 DIM VAR_UNK_B ARR_START NUM_i0000 NUM_i0004 AIDX PEND" 9


@REM ============================================================
@REM  DIM-time errors
@REM ============================================================

call %test% "arr.duplicate.def"
  @REM DIM A(3) : DIM A(5)
  @REM Duplicate definition = err 10.
  call :_runErr "VAR_UNK_A ARR_START NUM_i0003 DIM VAR_UNK_A ARR_START NUM_i0005 DIM" 10

call %test% "arr.duplicate.different.shape"
  @REM DIM A(3) : DIM A(2,3)
  @REM Duplicate detected regardless of new shape.
  call :_runErr "VAR_UNK_A ARR_START NUM_i0003 DIM VAR_UNK_A ARR_START NUM_i0002 NUM_i0003 DIM" 10


@REM ============================================================
@REM  Types via explicit suffix in postfix
@REM
@REM  These bypass `str encode` which can't safely round-trip `%`, `!`,
@REM  `"`, etc.  The lexer-level path for these is exercised indirectly
@REM  by the parser unit tests; here we just verify that ASSIGN_ARR /
@REM  AIDX honour the type tag on the VAR token and that the right
@REM  numeric facade is used on read.
@REM ============================================================

call %test% "arr.type.int.suffix"
  @REM DIM A%(3) : A%(1) = 10 : PRINT A%(1)
  @REM Integer array stores integers; PEND prints with leading space.
  call :_run "VAR_INT_A ARR_START NUM_i0003 DIM VAR_INT_A ARR_START NUM_i0001 NUM_i000A ASSIGN_ARR VAR_INT_A ARR_START NUM_i0001 AIDX PEND" " 10"

call %test% "arr.type.sng.suffix"
  @REM DIM A!(3) : A!(1) = 10 : PRINT A!(1)
  @REM Single array — int literal 10 promoted to sng on store.
  call :_run "VAR_SNG_A ARR_START NUM_i0003 DIM VAR_SNG_A ARR_START NUM_i0001 NUM_i000A ASSIGN_ARR VAR_SNG_A ARR_START NUM_i0001 AIDX PEND" " 10"

call %test% "arr.type.dbl.suffix"
  @REM DIM A#(3) : A#(1) = 10 : PRINT A#(1)
  call :_run "VAR_DBL_A ARR_START NUM_i0003 DIM VAR_DBL_A ARR_START NUM_i0001 NUM_i000A ASSIGN_ARR VAR_DBL_A ARR_START NUM_i0001 AIDX PEND" " 10"

call %test% "arr.type.str.suffix"
  @REM DIM S$(3) : S$(1) = "HI" : PRINT S$(1)
  @REM "HI" → STR_4849.  PEND prints strings with no leading space.
  call :_run "VAR_STR_S ARR_START NUM_i0003 DIM VAR_STR_S ARR_START NUM_i0001 STR_4849 ASSIGN_ARR VAR_STR_S ARR_START NUM_i0001 AIDX PEND" "HI"

call %test% "arr.type.str.default.empty"
  @REM DIM S$(3) : PRINT S$(0)
  @REM Unassigned string element is the empty string.
  call :_run "VAR_STR_S ARR_START NUM_i0003 DIM VAR_STR_S ARR_START NUM_i0000 AIDX PEND" ""


@REM ============================================================
@REM  Runtime bounds
@REM ============================================================

call %test% "arr.dim.from.variable"
  @REM I = 5 : DIM C(I) : C(5) = 50 : PRINT C(5)
  @REM Bounds expression evaluated at runtime, not parse time.
  call :_run "VAR_UNK_I NUM_i0005 ASSIGN VAR_UNK_C ARR_START VAR_UNK_I DIM VAR_UNK_C ARR_START NUM_i0005 NUM_i0032 ASSIGN_ARR VAR_UNK_C ARR_START NUM_i0005 AIDX PEND" " 50"

call %test% "arr.dim.from.expression"
  @REM N = 3 : DIM C(N+1) : C(4) = 7 : PRINT C(4)
  @REM Bound is an arbitrary expression.
  call :_run "VAR_UNK_N NUM_i0003 ASSIGN VAR_UNK_C ARR_START VAR_UNK_N NUM_i0001 ADD DIM VAR_UNK_C ARR_START NUM_i0004 NUM_i0007 ASSIGN_ARR VAR_UNK_C ARR_START NUM_i0004 AIDX PEND" " 7"


@REM ============================================================
@REM  Coexistence with scalar of the same name
@REM ============================================================

call %test% "arr.coexist.scalar.read"
  @REM A = 42 : DIM A(3) : A(1) = 100 : PRINT A
  @REM `A` (scalar) and `A()` (array) are separate variables.
  call :_run "VAR_UNK_A NUM_i002A ASSIGN VAR_UNK_A ARR_START NUM_i0003 DIM VAR_UNK_A ARR_START NUM_i0001 NUM_i0064 ASSIGN_ARR VAR_UNK_A PEND" " 42"

call %test% "arr.coexist.element.read"
  @REM A = 42 : DIM A(3) : A(1) = 100 : PRINT A(1)
  call :_run "VAR_UNK_A NUM_i002A ASSIGN VAR_UNK_A ARR_START NUM_i0003 DIM VAR_UNK_A ARR_START NUM_i0001 NUM_i0064 ASSIGN_ARR VAR_UNK_A ARR_START NUM_i0001 AIDX PEND" " 100"


@REM ============================================================
@REM  Future: OPTION BASE n  (not yet implemented)
@REM ============================================================
@REM Once OPTION BASE n is added these become positive tests:
@REM   "OPTION BASE 1 : DIM A(3) : A(1) = 5 : PRINT A(1)"  →  " 5"
@REM   "OPTION BASE 1 : DIM A(3) : PRINT A(0)"             →  err 9
@REM   "DIM A(3) : OPTION BASE 1"                          →  err (must be before any DIM)

exit /B


@REM ============================================================
@REM  Helpers
@REM ============================================================

@REM Helper: run pre-parsed postfix and check single-line stdout.
:_run
  set /a numTests+=1
  setlocal EnableDelayedExpansion
  call %GWSRC%\exec\_vars init
  call %GWSRC%\exec\_arrays init
  call %GWSRC%\exec\exec run "%~1" > "%GWTEMP%\_test.out" 2>&1
  set "_got="
  set /p "_got=" < "%GWTEMP%\_test.out"
  if "!_got!"=="%~2" (
    endlocal & set /a passedTests+=1
  ) else (
    echo FAILED: %~1
    echo   Expected: [%~2]
    echo        Got: [!_got!]
    endlocal & set /a failedTests+=1
  )
  exit /B


@REM Helper: run pre-parsed postfix and check errorlevel.
:_runErr
  set /a numTests+=1
  setlocal EnableDelayedExpansion
  call %GWSRC%\exec\_vars init
  call %GWSRC%\exec\_arrays init
  call %GWSRC%\exec\exec run "%~1" > "%GWTEMP%\_test.out" 2>&1
  set "_e=!ERRORLEVEL!"
  if "!_e!"=="%~2" (
    endlocal & set /a passedTests+=1
  ) else (
    echo FAILED err: %~1
    echo   Expected errlevel: %~2
    echo                 Got: !_e!
    endlocal & set /a failedTests+=1
  )
  exit /B
